apiVersion: v1
kind: Pod
metadata:
  name: jenkins-worker
  namespace: default
  labels:
    app: jenkins
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["cat"]
    tty: true
  - name: maven
    image: maven
    command: ["cat"]
    tty: true
  - name: golang
    image: golang:1.9
    command: ["cat"]
    tty: true
  - name: worker
    image: migueldavid/jenkins-worker
    command: ["cat"]
    tty: true
